/*
 * VuePresence.java
 *
 * Created on 5 avr. 2012, 11:48:52
 */
package vue;

import com.toedter.calendar.JDateChooser;
import controleur.CtrlAbstrait;
import controleur.CtrlPresence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author nbourgeois
 */
public class VuePresence extends VueAbstraite {
    
    DefaultComboBoxModel modeleJComboBoxEquipier;
    DefaultComboBoxModel modeleJComboBoxEtatPresence;
    
    /** Creates new form VuePresence */
    public VuePresence(CtrlAbstrait ctrl) {
        super(ctrl);
        modeleJComboBoxEquipier= new DefaultComboBoxModel();
        initComponents();
        this.setLocation(700, 300);
        modeleJComboBoxEtatPresence= new DefaultComboBoxModel();
        jComboBoxEquipier.setModel(modeleJComboBoxEquipier);
        jComboBoxEtatPresence.setModel(modeleJComboBoxEtatPresence);
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserDatePresence = new com.toedter.calendar.JDateChooser();
        jButtonQuitter = new javax.swing.JButton();
        jButtonEnregistrer = new javax.swing.JButton();
        jComboBoxEquipier = new javax.swing.JComboBox();
        jComboBoxEtatPresence = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Saisie de la présence des équipiers");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jLabel1.setText("Saisie d'une Absence / Présence");

        jLabel2.setText("Equipier : ");

        jLabel3.setText("Date : ");

        jDateChooserDatePresence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooserDatePresenceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jDateChooserDatePresenceMousePressed(evt);
            }
        });
        jDateChooserDatePresence.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDatePresencePropertyChange(evt);
            }
        });

        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });

        jButtonEnregistrer.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButtonEnregistrer.setText("Enregistrer");
        jButtonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerActionPerformed(evt);
            }
        });

        jComboBoxEquipier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxEtatPresence.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Etat : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDateChooserDatePresence, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15))
                                            .addComponent(jComboBoxEtatPresence, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addComponent(jComboBoxEquipier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jComboBoxEquipier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserDatePresence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEtatPresence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQuitter)
                    .addComponent(jButtonEnregistrer))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerActionPerformed
        ((CtrlPresence)controleur).presenceEnregistrer();
    }//GEN-LAST:event_jButtonEnregistrerActionPerformed

    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed
        ((CtrlPresence)controleur).presenceQuitter();
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ((CtrlPresence)controleur).presenceQuitter();
    }//GEN-LAST:event_formWindowClosing

    private void jDateChooserDatePresenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooserDatePresenceMouseClicked
       
    }//GEN-LAST:event_jDateChooserDatePresenceMouseClicked

    private void jDateChooserDatePresenceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooserDatePresenceMousePressed
     
    }//GEN-LAST:event_jDateChooserDatePresenceMousePressed

    private void jDateChooserDatePresencePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDatePresencePropertyChange
        ((CtrlPresence)controleur).presenceAfficher();
    }//GEN-LAST:event_jDateChooserDatePresencePropertyChange

    //-------------------------------------------------------
    //          Accesseurs et Mutateurs
    //-------------------------------------------------------
    public JButton getjButtonAnnuler() {
        return jButtonQuitter;
    }

    public void setjButtonAnnuler(JButton jButtonAnnuler) {
        this.jButtonQuitter = jButtonAnnuler;
    }

    public JButton getjButtonEnregistrer() {
        return jButtonEnregistrer;
    }

    public void setjButtonEnregistrer(JButton jButtonEnregistrer) {
        this.jButtonEnregistrer = jButtonEnregistrer;
    }

    public JDateChooser getjDateChooserDatePresence() {
        return jDateChooserDatePresence;
    }

    public void setjDateChooserDatePresence(JDateChooser jDateChooserDatePresence) {
        this.jDateChooserDatePresence = jDateChooserDatePresence;
    }

    public JComboBox getjComboBoxEtatPresence() {
        return jComboBoxEtatPresence;
    }

    public void setjComboBoxEtatPresence(JComboBox jComboBoxEtatPresence) {
        this.jComboBoxEtatPresence = jComboBoxEtatPresence;
    }

    public DefaultComboBoxModel getModeleJComboBoxEtatPresence() {
        return modeleJComboBoxEtatPresence;
    }

    public void setModeleJComboBoxEtatPresence(DefaultComboBoxModel modeleJComboBoxEtatPresence) {
        this.modeleJComboBoxEtatPresence = modeleJComboBoxEtatPresence;
    }


    public JComboBox getjComboBoxEquipier() {
        return jComboBoxEquipier;
    }

    public void setjComboBoxEquipier(JComboBox jComboBoxEquipier) {
        this.jComboBoxEquipier = jComboBoxEquipier;
    }

    public DefaultComboBoxModel getModeleJComboBoxEquipier() {
        return modeleJComboBoxEquipier;
    }

    public void setModeleJComboBoxEquipier(DefaultComboBoxModel modeleJComboBoxEquipier) {
        this.modeleJComboBoxEquipier = modeleJComboBoxEquipier;
    }


    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JComboBox jComboBoxEquipier;
    private javax.swing.JComboBox jComboBoxEtatPresence;
    private com.toedter.calendar.JDateChooser jDateChooserDatePresence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
